language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install
  - composer create-project
  - php bin/initialize-test-db.php
  - php artisan serve --quiet &> /dev/null &
  - sleep 2

script:
  - vendor/bin/codecept -c vendor/inklabs/kommerce-templates/codeception.yml run acceptance
