language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install
  - composer create-project
  - php artisan serve --quiet &> /dev/null &
  - sleep 3
  - curl -s http://localhost:8000/dummy-data/create-dummy-product > /dev/null
  - curl -s http://localhost:8000/dummy-data/create-dummy-coupon > /dev/null

script:
  - vendor/bin/codecept -c vendor/inklabs/kommerce-templates/codeception.yml run acceptance
