language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install
  - composer create-project
  - php bin/initialize-test-db.php
  - php artisan serve --quiet &> /dev/null &
  - sleep 2

script:
  - vendor/bin/codecept -c vendor/inklabs/kommerce-templates/codeception.yml run acceptance

notifications:
  slack:
    rooms:
      - secure: "MVKewuhNzuK8T6WDXmKUPKcxLInfrBvHyUDyVUowAVD5TX7Eq2uZ80P/jg3e8OzslI/CePvMAUmjebK6RpeskGnTdyHXm0phZjyu7t/e9ZjlvCnAYKXWjz+rLJ6MsMhwiXdsXILXCu0PPjjXgPVhoJoTwfw9CHgqEb064bGz1McONFlLXJYfgU0UsZyYMetE/JPIOXOE4bLcd7P6E4Se6WeeAHK4qy3nEb9EGQsZgTzMthMHpkIqpj6TFQ5kEGTay3XTkrEG3ekCBm6QWDdKFwSFvnzgUs5m+SRloUxUqZqyfZvFl/6hhHpEykkwMmvKnBd8Qgu1YqZ8lunIYpsCgyCk75PQpa3PLaULzqRrdwUxSnbaJiif4YeSEGgOEi6zNwcv3ur0iSYCQl3/ZACwqYtkrdBDcCnnSlPqdeo5I4S7oheJqncEZchOGwBKx3LSwQkthgdHq54hsG1MYnYrGVgS4jL/MulEo4eixngDWBFC4gW1e3PDHj9w/MSOdJCtH+TGLpJW2NvvKV+1rtjMiW6phHOmPSPl8s75SvYpkx1tzvTcwcyW8OnN3TjAq/aJThsXbpzRidpvwsynl8vYQ2+BVmz6hG2yqhlnPhkRLUGUGCKeuvtg49XTQkeJeB6WNKNJpN9ZqXnS2piR2NjH1F1tdV6Rn2G+v+8Gy+sLDcs="
    on_success: change
    on_failure: always
