language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install
  - composer create-project
  - php bin/initialize-test-db.php
  - php artisan serve --quiet &> /dev/null &
  - sleep 2

script:
  - vendor/bin/codecept -c vendor/inklabs/kommerce-templates/codeception.yml run acceptance

notifications:
  slack:
    secure: Txja/GVybEYYJO2CM8Z7lS9T0lMCLa8s1PDJrlN0w+CDhshAICJM5TfoBe3O0fleGaJnpXm3jUoyoFtAS7sfdYO7iVd+FLiNCdfEWeQwAEUHkz0DCu4rIPLIKtyQBaTT48JgXXkPTDjGnDdd/RR31iw9imlrbzpkGfjL766W99Otco14pBhMHZki/Sym1mss3Hd3McIVCompuhrxW6NlymffM6jT+0tq+QeiNLDnuv1a7H8jHFLbx+KwxcCdNHhAaOXCLIpzlT1w0nl0AMDaERqL0dRnmKFaPgE7rm/tBkUUQj6wmR6QKELtEBuXdTu4HHbSOBG5hH3qS0G1KU925UYz1A+wdR/QFVm6mtSrVCl/ue7YCMfPxNSRc8IqiOUfcPbuz+NYp5yRTsNbTGzBh5xA15tkxTDVqj345A3+jUDYJ7cZU0m3/Rthputmc1iwDeF4dBl70mqu2LJQfOTvyy4bWAW3n+tUThpRFgoqbuEYW73LqOsVj8mkEMOPxuB0yX12dcpNYRJ/wyWrs61waQhV6huUclbUXIGmZR4oCfJF8iIPzxYqQisqigolXlSFLKC0YnDgWMb8tvLjq0tDu/ugUV2CYdJOYNG12TXvZoXqpH4dezG+WIJREy5exy4cjbrxx1zsbHbBJcHYXoGeitYEWM3/q3ouW82exLrFlq0=
